### PR TITLE
make ON OFF actuator more flexible

### PR DESCRIPTION
**Pull request by 1technophile**
enable to choose the pin when sending the MQTT command

### CODE REVIEW

**Comment by 1technophile** [comment]
@paulantondeen

here is an environment definition to test the modification

```ini
[env:nodemcuv2-ONOFFPILIGHT]
platform = ${com.esp8266_platform}
board = nodemcuv2
lib_deps =
  ${com-esp.lib_deps}
  ${libraries.esppilight}
  ${libraries.esp8266_mdns}
  ${libraries.wire}
build_flags = 
  ${com-esp.build_flags}
  '-DZgatewayPilight="Pilight"'
  '-DZactuatorONOFF="ONOFF"'
  '-DGateway_Name="OpenMQTTGateway_ESP8266_ONOFFRF"'
board_build.flash_mode = dout
```

**Comment by PaulAntonDeen** [comment]
So far it seems to work, I got it compiled, uploaded and connected to my mqqt server. On the 0.91 433Mhz build that I have on my other MCU I get a constant blue LED when it is on and connected. I don't get that on this one. I need to build a little test setup to see if it will switch the relays so that test will come later.

**Comment by PaulAntonDeen** [comment]
If I switch pin15 I expect D8 to toggle high low, correct? Per this image:
nodemcu_pins

**Comment by 1technophile** [comment]
> If I switch pin15 I expect D8 to toggle high low, correct? Per this image:
> nodemcu_pins

Yes exactly 


```
mosquitto_pub -t home/OpenMQTTGateway_ESP8266_ONOFFRF/commands/MQTTtoONOFF -m '{"pin":15,"state":0}'

mosquitto_pub -t home/OpenMQTTGateway_ESP8266_ONOFFRF/commands/MQTTtoONOFF -m '{"pin":15,"state":1}'
```

**Comment by PaulAntonDeen** [comment]
Pin 15 works great! Pin 14 (D5) seems to not switch and is always high. Which pins should I be able to toggle?

**Comment by PaulAntonDeen** [comment]
D0 works
D1 works
D2 works
D3 initialized high, toggles correct
D4 initialized high, toggles correct
D5 doesn't work

it seems to periodically forget my wifi and MQTT broker credentials...

**Comment by PaulAntonDeen** [comment]
Correction, D5 works initialized high
D6 works
Lost Wifi again

**Comment by PaulAntonDeen** [comment]
D7 works
D8 works

**Comment by 1technophile** [comment]
Pins that you are able to toggle depends on your board, you have to check the pinout

**Comment by 1technophile** [comment]
Thanks for the feedback, if you don't have any concern I'm going to merge the PR

**Comment by PaulAntonDeen** [comment]
If the environment section is added to the platformio.ini so that it can be uncommented to be enabled then everything is working great!

**Comment by 1technophile** [comment]
Done but on prod_env.ini.example.
To use it just rename the file to prod_env.ini and let inside your production environments

**Pull request merged**
