### PR TITLE
Add new light sensor Temt6000 using a d1 mini

### PR DESCRIPTION
**Pull request by diepeterpan**
## Description:

Add new ambient light sensor Temt6000 using a d1 mini

image

## Checklist:
  - [ #] The pull request is done against the latest development branch
  - [ #] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ #] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
I'm a bit worry when I see the commit history. Could you rebase against development please, it would easier to read the PR

**Comment by diepeterpan** [comment]
> I'm a bit worry when I see the commit history. Could you rebase against development please, it would easier to read the PR

Let me try, not an expert on rebase, usually just check the [Files changed] - https://github.com/1technophile/OpenMQTTGateway/pull/1545/files

Hang on, I am going to try a rebase.

**Comment by diepeterpan** [comment]
> > I'm a bit worry when I see the commit history. Could you rebase against development please, it would easier to read the PR
> 
> Let me try, not an expert on rebase, usually just check the [Files changed] - https://github.com/1technophile/OpenMQTTGateway/pull/1545/files
> 
> Hang on, I am going to try a rebase.

I see a lot of changes re which making is not difficult and the changed code is not working for my PIR:

  '-DWifiGMode=true'
  '-DWifiPower=WIFI_POWER_11dBm'

**Comment by diepeterpan** [comment]
> > > I'm a bit worry when I see the commit history. Could you rebase against development please, it would easier to read the PR
> > 
> > 
> > Let me try, not an expert on rebase, usually just check the [Files changed] - https://github.com/1technophile/OpenMQTTGateway/pull/1545/files
> > Hang on, I am going to try a rebase.
> 
> I see a lot of changes re which making is not difficult and the changed code is not working for my PIR:
> 
> '-DWifiGMode=true' '-DWifiPower=WIFI_POWER_11dBm'

Cant I rather try and merge commit or something, I now understand that the rebase is going through all the previous changes to apply, a nightmare.

**Comment by 1technophile** [comment]
Alternatively, you can copy your work, close this PR, fetch the development version.
Paste your work, identify the differences, verify that it works and push a new branch.
If the branch build propose a new PR

**Comment by diepeterpan** [comment]
> Alternatively, you can copy your work, close this PR, fetch the development version. Paste your work, identify the differences, verify that it works and push a new branch. If the branch build propose a new PR

Fully agree, will do that tomorrow, but late now.

**Pull request closed without merging**
