### PR TITLE
Add support for multiple IR LEDs

### PR DESCRIPTION
**Pull request by vossim**
- IR_EMITTER_PIN renamed to IR_EMITTER_PIN_0
- Added IR_EMITTER_PIN_1, can be expanded to more IR emitters if
  required

### CODE REVIEW

**Comment by jmw6773** [comment]
Are both IR pins sending the same data. If this is is the case, why not just put the IR LED's in parallel, each with a current limiting resistor? I have this on my gateways, one with 5 IR LED's in parallel without issues. Just be sure to drive them using a transistor or mosfet.

With multiple IR LED's transmitting the same data, one after the other (they don't transmit synchronously), a receiving device may receive both signals and behave oddly. (Mute button for TV mutes then immediately unmutes, etc)

**Comment by vossim** [comment]
The output pin can be "selected" by passing in a `short` named `out` in the JSON.

```{"value":46505948479624,"protocol_name":"DENON","out":0}```
Would trigger the default emitter pin

```{"value":46505948479624,"protocol_name":"DENON","out":1}```
Would trigger the second emitter

**Comment by 1technophile** [comment]
May you indicate the use case behind this proposal?

**Comment by vossim** [comment]
I'm using this to control multiple devices using the same IR signals independently. So I can control 2 similar receivers using one esp8266, otherwise I would need 2 OMG devices.

**Comment by 1technophile** [comment]
Thanks for the PR, nevertheless I think there is other way to answer to your use case.

If you want an integration that answer it, I would propose to do a PR with the capacity to change the IR emitter pin when sending or by a special MQTT command.
We can discuss about that on the design principle if you are interested.

**Pull request closed without merging**
