### PR TITLE
[SYS] Bump ESP32 platform to v6.1.0 and ESP8266 to v4.1.0

### PR DESCRIPTION
**Pull request by 1technophile**
## Description:
Update ESP platforms

### Resolved Issues

* ZdisplaySSD1306 module when included causes a immediate reboot loop - #1551

### Open Issues

* Usage of GPIO pins greater than 39 causes excessive logging

```
[    41][E][esp32-hal-gpio.c:102] __pinMode(): Invalid pin selected
[    41][E][esp32-hal-gpio.c:102] __pinMode(): Invalid pin selected
E (40) gpio: gpio_set_level(226): GPIO output gpio_num error
E (45) gpio: gpio_set_level(226): GPIO output gpio_num error
E (51006) gpio: gpio_set_level(226): GPIO output gpio_num error
E (51012) gpio: gpio_set_level(226): GPIO output gpio_num error
E (51017) gpio: gpio_set_level(226): GPIO output gpio_num error
```
* Save configuration to flash triggers an exception/restart on a lily board

```
assert failed: heap_caps_free heap_caps.c:360 (heap != NULL && “free() target pointer is outside heap areas”)

Backtrace: 0x40083c69:0x3ffb2700 0x4008dcc1:0x3ffb2720 0x40093a45:0x3ffb2740 0x40084126:0x3ffb2870 0x40093a75:0x3ffb2890 0x40102e41:0x3ffb28b0 0x40102e51:0x3ffb28d0 0x400db272:0x3ffb28f0 0x400db3db:0x3ffb2c70 0x400db4f9:0x3ffb2cb0 0x400de686:0x3ffb2cd0 0x400dea63:0x3ffb3040 0x401a626d:0x3ffb30f0 0x400e641a:0x3ffb3110 0x400e64c1:0x3ffb3130 0x400e659e:0x3ffb3170 0x400e6751:0x3ffb31e0 0x400df386:0x3ffb3230 0x400df457:0x3ffb3250 0x401057e1:0x3ffb3290
  #0  0x40083c69:0x3ffb2700 in panic_abort at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/panic.c:408
  #1  0x4008dcc1:0x3ffb2720 in esp_system_abort at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/esp_system/esp_system.c:137
  #2  0x40093a45:0x3ffb2740 in __assert_func at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/newlib/assert.c:85
  #3  0x40084126:0x3ffb2870 in heap_caps_free at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_caps.c:360
      (inlined by) heap_caps_free at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_caps.c:345
  #4  0x40093a75:0x3ffb2890 in free at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/newlib/heap.c:39
  #5  0x40102e41:0x3ffb28b0 in String::invalidate() at /Users/sgracey/.platformio/packages/framework-arduinoespressif32/cores/esp32/WString.cpp:163
  #6  0x40102e51:0x3ffb28d0 in String::~String() at /Users/sgracey/.platformio/packages/framework-arduinoespressif32/cores/esp32/WString.cpp:147
  #7  0x400db272:0x3ffb28f0 in SSD1306Config_save() at main/ZdisplaySSD1306.ino:224
```

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by Argafal** [comment]
This pull request causes an issue on lolin32 boards, documented here: 
https://community.openmqttgateway.com/t/version-bump-to-espressif-6-1-0-breaks-omg-on-lolin32/2329

I assume it's just a missing pin definition somewhere. A helpful pointer in the right direction would be appreciated! :)

**Comment by ilgrank** [comment]
I can also add that I tried the 6.10, and while I had not any (new) issue, is consumed on average 10kb more than 5.x

**Comment by 1technophile** [comment]
@Argafal this should be fixed with my last commits

**Comment by 1technophile** [comment]
@ilgrank yes, me too, and even more, but I found this new version to be far more stable regarding BT gateway

**Pull request merged**
