### PR TITLE
Added Thingpulse ESP32 Gateway

### PR DESCRIPTION
**Pull request by hallard**
## Description:

- Added Thingpulse ESP32 Gateway
- Alllow change default brightness of Fast LED behavior
- Alllow change default led action (one for info, one for error, one for send/receive)

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by hallard** [comment]
@1technophile I let you check file format error, not sure what's going wrong, tried 3 times without any success, I really love when github says wrong format but not telling you where and why, forcing you to spend more time trying to fix this format error than creating a working and usefull PR

**Comment by 1technophile** [comment]
@hallard format fixed. I have used the right-click -> Format document option on VSC, from inside the file. You may need to have the 'clang-Format' extension installed

**Comment by 1technophile** [comment]
Thanks for the PR. Could you add the new board here, also:
https://github.com/1technophile/OpenMQTTGateway/blob/ec21cbb8800e0aef82f72411665155ad13179135/.github/workflows/build.yml#L10

For faster CI from commits, we have listed the environments there.
If not added your board will still be released but it is not checked against CI.

Also, we list the boards in the documentation for the web upload:
https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/upload/web-install.md

**Comment by hallard** [comment]
> @hallard format fixed. I have used the right-click -> Format document option on VSC, from inside the file. You may need to have the 'clang-Format' extension installed

As easy as that, thank you for the tip :-)

I'll check the documentation, FYI it's not my board but Daniel's one that you may know for writing excellent and well known ESP OLED library :-)

**Comment by marcelstoer** [comment]
ThingPulse co-founder here.

Thanks Charles 👍 

@1technophile would you accept a PR to have [our gateway](https://thingpulse.com/product/espgateway/) listed in your [List of compatible boards](https://compatible.openmqttgateway.com/index.php/boards/)?

**Comment by hallard** [comment]
> Thanks Charles 👍

Hii @marcelstoer You're welcome, please note that I did not add Ethernet support, not sure if OMG can manage chip used LA8720.

Edit looks like support for LAN8720 exists in this [branch](https://github.com/1technophile/OpenMQTTGateway/blob/ec21cbb8800e0aef82f72411665155ad13179135/main/User_config.h#L87-L106) but not in `development` one, @1technophile may be we can add it it it works?
 
> @1technophile would you accept a PR to have [our gateway](https://thingpulse.com/product/espgateway/) listed in your [List of compatible boards](https://compatible.openmqttgateway.com/index.php/boards/)?

I think this is what he asked for, I can add that on this PR but if you prefer you can do it on another one it's not problem just let me know

**Comment by hallard** [comment]
I think for Ethernet the right config is the following, need to try this one, but no time today on my side

```cpp
#ifdef ESP32_ETHERNET
#  define ETH_PHY_ADDR  1
#  define ETH_PHY_TYPE  ETH_PHY_LAN8720
#  define ETH_PHY_POWER 17
#  define ETH_PHY_MDC   23
#  define ETH_PHY_MDIO  18
#  define ETH_CLK_MODE  ETH_CLOCK_GPIO0_IN
#endif
```

**Comment by marcelstoer** [comment]
>>@1technophile would you accept a PR to have [our gateway](https://thingpulse.com/product/espgateway/) listed in your [List of compatible boards](https://compatible.openmqttgateway.com/index.php/boards/)?

>I think this is what he asked for

I was talking about something else but I just realized those devices are managed by a WooCommerce shop and I can't just send a PR :)

**Comment by 1technophile** [comment]
@marcelstoer I will add it to the list!

**Comment by DigiH** [comment]
> ThingPulse co-founder here.

Apologies for hijacking this thread a bit, but too good an opportunity @marcelstoer 

Funnily enough I submitted a [decoder for the SCD4X](https://github.com/theengs/decoder/pull/234) a day before @hallard posted this PR. Looking at the products on your site I found that your  [AMo – CO2 monitor](https://thingpulse.com/product/amo-co2-monitor/) uses exactly this sensor, and should therefore be recognised and decoded. Any confirmation from your side would be great so that we could also include the AMo – CO2 monitor in the compatible [BLE devices list](https://decoder.theengs.io/devices/devices_by_brand.html).

Thanks

**Comment by hallard** [comment]
Whoo so many great people out there, did not expected so much while creating this PR, anyway I've just added the ThingPulse Gateway Ethernet also but I do not succeded to works on Ethernet

Always got the error

```
************* WELCOME TO OpenMQTTGateway **************
N: OpenMQTTGateway Version: version_tag
E (1034) emac: Timed out waiting for PHY register 0x2 to have value 0x0007(mask 0xffff). Current value 0x0000
E (2035) emac: Timed out waiting for PHY register 0x3 to have value 0xc0f0(mask 0xfff0). Current value 0x0000
E (2036) emac: Initialise PHY device Timeout
[E][ETH.cpp:105] begin(): esp_eth_enable error: -1
```

Looking on schematics of thingpulse Ethernet Gateway here 
https://thingpulse.com/product/espgateway-ethernet-esp32-wifi-ble-gateway-with-rj45-ethernet-connector/
state the following pinout (only one that differs from default Olimex ESP32 Ethernet)
```cpp
#  define ETH_PHY_POWER 17
#  define ETH_CLK_MODE  ETH_CLOCK_GPIO0_OUT // Not sure about this one
```

image


But looking at code on github on code using your ESP32 gateway Ethernet
https://github.com/ThingPulse/esp32-gateway-paxcounter/blob/master/src/settings.h#L6-L12
state other wiring
```cpp
#define ETH_CLK_MODE    ETH_CLOCK_GPIO16_OUT
#define ETH_POWER_PIN   5
```

So I'm a bit lost on how I need to declare in OMG, anyway I tried both plus some mix without any success, so any help from @marcelstoer or @squix78 would be helpfull

**Comment by 1technophile** [comment]
@marcelstoer any pointers for the issue of @hallard and the question of @DigiH ?

**Comment by hallard** [comment]
I have the wrong network chip on my PCB ENC28J60 so I’m waiting new one sent by Daniel to Check again, may be there is just no issue.
Anyway if ENC28J60 is supported I can give a try

**Comment by 1technophile** [comment]
@hallard should we integrate the PR with Wifi only, and open a new one when we have the information about the ethernet module ?

**Comment by hallard** [comment]
I received the new board, just need to test it but I've got too much work for now that I do not have idle time to play with. may be next week if you can wait until there?

**Comment by 1technophile** [comment]
I can wait, no hurry!

**Comment by hallard** [comment]
Just tested the new board received with LAN8720, just works, I think we can merge this one.

Oh BTW I added parameters to be able to change led brightness at compile time, need to be 255 instead of default 20 for this GW :-)

**Comment by 1technophile** [comment]
Cool thanks, I think there may be an issue with the rebase, as I see 57 files modified

**Comment by hallard** [comment]
yes my bad I merged your changes of development in my branch thingspulse before, sorry about that, easy to fix?

**Comment by 1technophile** [comment]
I just tried, and I need to resolve the conflict of many files. If you don't mind fetching dev and creating a new branch from it please, it would help

**Comment by hallard** [comment]
will try something

**Comment by hallard** [comment]
ok lost everything still don't understand how can that be possible I have no more changes of my branch, will check later, I'm fade up not being a git guru ..

**Comment by hallard** [comment]
Fixed in #1369

**Comment by 1technophile** [comment]
@marcelstoer, we added the gateway to the list of compatible devices. Could you help @DigiH with his question?

**Comment by marcelstoer** [comment]
@1technophile @DigiH does https://github.com/1technophile/OpenMQTTGateway/pull/1324#issuecomment-1321165816 ask me to confirm that our AMo CO2 monitor is compatible with the OpenMQTTGateway (sorry, not sure)? If so, I'd have to set up a gateway first and test this. However, given that the Sensirion BLE mobile app works just fine with the AMo I'd assume it'll work just fine with the decoder here.

**Comment by DigiH** [comment]
> @1technophile @DigiH does [#1324 (comment)](https://github.com/1technophile/OpenMQTTGateway/pull/1324#issuecomment-1321165816) ask me to confirm that our AMo CO2 monitor is compatible with the OpenMQTTGateway (sorry, not sure)? If so, I'd have to set up a gateway first and test this. However, given that the Sensirion BLE mobile app works just fine with the AMo I'd assume it'll work just fine with the decoder here.

Hi @marcelstoer,

yes, that was basically my query, if your AMo CO2 monitor is OpenMQTTGateway, Theengs Gateway, Theengs Explorer and Theengs App for Android and iOS (with the next ipdate) compatible. 
I would assume so, but before adding the AMo CO2 monitor to our docs and compatible devices list some form of confirmation would be needed.
As an alternative to installing OpenMQTTGateway or Theengs Gateway for testing purposes a screenshot of some AMo CO2 monitor advertising manufacturerdata with nRFConnect should also be sufficient.

Or another possibility - what desktop OS are you using?

**Comment by marcelstoer** [comment]
@DigiH I'm on macOS. Below is what I get out of LightBlue for the AMo. It shows up as "S", representing **S**ensirion I guess. We use their https://github.com/Sensirion/arduino-ble-gadget library in the AMo firmware.

Screen Shot 2023-02-05 at 23 48 00

**Comment by DigiH** [comment]
@marcelstoer Thanks for the info and the data sample. We'll slightly have to adjust the datalength then the AMo should be fully supported by Theengs Decoder and be included in OpenMQTTGateway and the other projects using it.

**Pull request closed without merging**
