### PR TITLE
[BT] Restarting the tasks is not enough in case of BLE stack stuck

### PR DESCRIPTION
**Pull request by 1technophile**
## Description:
So restart the ESP instead

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by eljojo** [comment]
@1technophile Hi Florian, would you mind cutting a new release? been observing times without data capture since the last update that I think could be fixed by this! (PS: great job on the web ui and gateway in general!)

**Comment by 1technophile** [comment]
You can try the development version from here:
https://docs.openmqttgateway.com/dev/ and report if it solves your issue.

**Comment by eljojo** [comment]
I think it does! 
image

before seeing your message it came to mind I could [rebuild by forking the repo and pushing an empty commit](https://github.com/eljojo/OpenMQTTGateway/actions/runs/6117082838), so I did that and extracted the upgrade image from the artifacts. Been running it for a few days and it seems to restart appropriately. 

it's interesting to be between 60k-65k seconds

**Comment by eljojo** [comment]
I wonder why the restarts became necessary, I couldn't observe any other pattern that would indicate. It seemed to not happen before the web ui.

**Comment by 1technophile** [comment]
The restart is necessary due to this issue 
https://github.com/espressif/arduino-esp32/issues/5860

**Pull request merged**
