### PR TITLE
Circuit diagram updated

### PR DESCRIPTION
**Pull request by syssi**
A VCC of 5V is out of specification for all components (bme280, bh1750 & esp8266).

### CODE REVIEW

**Comment by HannesDi** [comment]
Hey Syssi,

i dont know where you get your Modules...

But Nope...

Thats not correct....

They all running fine at 5V (They are all Voltage tolerant)

https://de.aliexpress.com/item/New-product-Wireless-module-NodeMcu-Lua-Wifi-ESP8266MOD-WIFI-Network-Development-Board-Based-ESP8266-High/32497217750.html

https://de.aliexpress.com/item/Hohe-Genauigkeit-BME280-Digital-Sensor-Temperatur-Luftfeuchtigkeit-Luftdruck-Sensor-Modul-GY-BME280-I2C-SPI-1-8/32672210336.html

https://de.aliexpress.com/item/New-BH1750FVI-Digital-Light-intensity-Sensor-Module-For-Ar-3V-5V/1859067467.html

Exept you build your complete Hardware from scratch..

When you solder the BH1750 and the ESP8266 Chips yourself on a custom PCB then you are right but then you need design all other stuff like pullup/pulldown resistors and so on...

OR when you buy the Cheap 3.3V fixed Voltage Module.... like this:
**DO NOT BUY THIS ->** https://de.aliexpress.com/item/GY-BME280-3-3-precision-altimeter-atmospheric-pressure-BME280-sensor-module/32688607454.html

We are talking about Module to Module not Chip to Chip

Best Regards
Hannes

**Comment by Landrash** [comment]
A compromise would be to write 3,3-5V to accommodate the "cheaper" sensors.

**Comment by syssi** [comment]
You are right! If some kind of voltage level shifter is involved the esp8266 is safe.

**Comment by syssi** [comment]
The arduino uno has a 5V TTL. Without a voltage level shift the cheap component will be in danger.

**Pull request closed without merging**
