### PR TITLE
Add env for Lolin Wemos D1 mini with CC1101

### PR DESCRIPTION
**Pull request by vi7**
## Description:

1. Add env for Lolin (Wemos) D1 Mini with CC1101 transceiver

Network related parameters (`-DNET_IP` etc.) are dependant on the feature delivered by #1715

NOTE: My editor automatically fixed some redundant spaces. Pls let me know if this is not needed

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
Thanks for the PR. I'm not sure of the value of adding a new environment for CC1101 and an ESP8266 based board, as we have already `nodemcuv2-rf-cc1101`

Do you know that you can store your environment into a prod_env.ini file separate from environments.ini ?

**Comment by vi7** [comment]
@1technophile yep, `prod_env.ini` is exactly how I'm using it right now. The reason for the PR is that `nodemcuv2-rf-cc1101` appeared to be incompatible with Wemos D1 mini boards as-is, so I thought dedicated env could be helpful for people who are using D1 mini board.

I'm ok with any decision from your side however.

**Comment by 1technophile** [comment]
Let's add it as an example only in this case (commented)

**Comment by vi7** [comment]
@1technophile I've moved D1 mini example to the `prod_env.ini.example` file

**Comment by 1technophile** [comment]
Thanks

**Pull request merged**
