### PR TITLE
Fix ClearGlass CGG1 and CGP1W sensors recognition

### PR DESCRIPTION
**Pull request by Nikolay-Ch**
Fix https://github.com/1technophile/OpenMQTTGateway/issues/845 issue

### CODE REVIEW

**Review by 1technophile — COMMENTED** [review]
Thanks for the PR,
Would it be possible to merge also these 2 blocks:
``` c
      Log.trace(F("Is it a CGG1" CR));
      if (strstr(service_data, "080774") != NULL) {
        Log.trace(F("CGG1 method 2" CR));
        BLEdata.set("model", "CGG1");
        if (device->sensorModel == -1)
          createOrUpdateDevice(mac, device_flags_init, CGG1);
        return process_cleargrass(BLEdata, false);
      }
      Log.trace(F("Is it a CGG1" CR));
      if (strncmp(service_data, "8816", 4) == 0) {
        Log.trace(F("CGG1 method 3" CR));
        BLEdata.set("model", "CGG1");
        if (device->sensorModel == -1)
          createOrUpdateDevice(mac, device_flags_init, CGG1);
        return process_cleargrass(BLEdata, false);
      }
```

and use

```
(strncmp(service_data, "080774", 6) == 0)
```

**Comment by Nikolay-Ch** [comment]
> Thanks for the PR,
> Would it be possible to merge also these 2 blocks:
> 
> ```c
>       Log.trace(F("Is it a CGG1" CR));
>       if (strstr(service_data, "080774") != NULL) {
>         Log.trace(F("CGG1 method 2" CR));
>         BLEdata.set("model", "CGG1");
>         if (device->sensorModel == -1)
>           createOrUpdateDevice(mac, device_flags_init, CGG1);
>         return process_cleargrass(BLEdata, false);
>       }
>       Log.trace(F("Is it a CGG1" CR));
>       if (strncmp(service_data, "8816", 4) == 0) {
>         Log.trace(F("CGG1 method 3" CR));
>         BLEdata.set("model", "CGG1");
>         if (device->sensorModel == -1)
>           createOrUpdateDevice(mac, device_flags_init, CGG1);
>         return process_cleargrass(BLEdata, false);
>       }
> ```
> 
> and use
> 
> ```
> (strncmp(service_data, "080774", 6) == 0)
> ```

I will do it... But why you want ro check service data with 080774 seqience? Third byte: 74 is the last byte of the MAC-address of the sensor, so, I think, that you do not need to use it in comparision.

**Comment by Nikolay-Ch** [comment]
Also, I found this information about old Advertising packet for the CGG1 device:
https://github.com/atc1441/ATC_MiThermometer/issues/3

I will refactor all three checks...

**Comment by 1technophile** [comment]
> 0807743e10342d580104c3002c0202012a. Third byte 74 is the last byte of the MAC-address of the sensor 743e10342d58. So I think, it not needed in comparison.

Good catch, thanks for the PR

**Pull request merged**
