### PR TITLE
Added GPIO Input

### PR DESCRIPTION
**Pull request by QuagmireMan**
Hopefully this is the correct way to submit the pull request.

### CODE REVIEW

**Comment by QuagmireMan** [comment]
Sorry,  I am still trying to figure out how to do this appropriately. I think the files should be there now.

I am a little unsure on how to remove:
`#ifdef ZsensorGPIOInput
  #include "config_RFM69.h"
#endif`

**Comment by 1technophile** [comment]
You can modify it on your repository and repush the file

**Comment by QuagmireMan** [comment]
I apologize, but I seemed to create a new PR when I made the changes.  Should we delete it all and try again in a new single PR?

**Comment by 1technophile** [comment]
yes we can do it like that no problem

**Pull request closed without merging**
