### PR TITLE
[OTA] Capability to disable Firmware Update on ESP32 WEB

### PR DESCRIPTION
**Pull request by bwynants**
## Description:

there is a compile error when '-UMQTT_HTTPS_FW_UPDATE'  is set in the build flags with an ESP32

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
Thanks for the PR,

Could you add the macro to this environment:
https://github.com/1technophile/OpenMQTTGateway/blob/4b8dfbea42488c464a8bdb3cc613c81a799fb4a8/environments.ini#L51
This way it will be tested by the CI

**Comment by NorthernMan54** [comment]
@bwynants Question - Why do you have the MQTT_HTTPS_FW_UPDATE directive set ?  Should the scope of  MQTT_HTTPS_FW_UPDATE be changed to still enable the WebUI firmware upgrade use case ?

**Comment by bwynants** [comment]
> @bwynants Question - Why do you have the MQTT_HTTPS_FW_UPDATE directive set ? Should the scope of MQTT_HTTPS_FW_UPDATE be changed to still enable the WebUI firmware upgrade use case ?

because i do not want that kind of updating? i upload my firmware updates via 'ota' saves me some space on the ESP

**Comment by bwynants** [comment]
> This way it will be tested by the CI

but CI would not test updates via WEB UI anymore. do you want that?

**Comment by 1technophile** [comment]
> but CI would not test updates via WEB UI anymore. do you want that?

It will be tested by the other environments

**Comment by 1technophile** [comment]
Thanks

**Pull request merged**
