### PR TITLE
Platfomio libraries definition update

### PR DESCRIPTION
**Pull request by 1technophile**
complete the name of htu21 library,
remove spi library include in zgatewayRFM69
#690 
add github full path when the owner of the library is present with the repository name

### CODE REVIEW

**Comment by 1technophile** [comment]
Waiting for the PIO [library crawler ]( library crawler to update PIO’s lib page)to update the [PIO RFM69 version](https://platformio.org/lib/show/92/RFM69?utm_source=platformio&utm_medium=piohome) before relaunching the CI

**Comment by jmw6773** [comment]
I had to specify the RFM69 github repo and change the spiflash commit number directly in order to compile correctly on my computer.
Looks like the Low-Power library will need to be specified too. (I think it's only used for RFM69 on ATMEL chips.)

```
[libraries]
rfm69 = https://github.com/LowPowerLab/RFM69@2e915ea
rfm69spi = https://github.com/lowpowerlab/spiflash@9c0c2b9
rfm69_low-power = Low-Power@1.6

[env:atmega-all]
lib_deps =
  ${libraries.rfm69}
  ${libraries.rfm69spi}
  ${libraries.rfm69_low-power}
```

**Comment by 1technophile** [comment]
> Looks like the Low-Power library will need to be specified too. (I think it's only used for RFM69 on ATMEL chips.)

Thanks for pointing that.

> I had to specify the RFM69 github repo and change the commit number directly for RFM69 and SPIFlash in order to compile correctly on my computer.

I will relaunch the CI tomorrow, and if it fails again I will go this way

**Comment by jmw6773** [comment]
Just read that `Tags` can also specified, so that might be an easier to read way to go instead of commit versions.

[libraries]
rfm69 = https://github.com/LowPowerLab/RFM69#1.4.0
rfm69spi = https://github.com/lowpowerlab/spiflash#101.1.2

This is an annoying change for PlatformIO, especially since it doesn't seem to have been announced or documented well. Hopefully they'll review and find a better implementation in the future.

Glad you opened a ticket and was able to get help quickly.

**Comment by 1technophile** [comment]
> I had to specify the RFM69 github repo and change the commit number directly for RFM69 and SPIFlash in order to compile correctly on my computer.
Looks like the Low-Power library will need to be specified too. (I think it's only used for RFM69 on ATMEL chips.)

This worked, thanks!

**Pull request merged**
