### PR TITLE
 Check GPIOInput state on demand

### PR DESCRIPTION
**Pull request by orxaz**
OMG publish when GPIOInput state changes, but would be nice to be able to check it on demand, asking on a topic for example, or the state to be reported periodically.

### CODE REVIEW

**Comment by 1technophile** [comment]
Hi,

Thanks for proposing a PR.

It seems that your fork was not updated against this repository `development` branch, could you try to create a new branch from this `development` branch and apply your modifications in it?
You can after submit a PR by comparing your branch and the `development `one, to be valid your PR should only contain the modifications corresponding to the PR goal.

**Comment by orxaz** [comment]
Hi.

But must I insert the code changes?

**Comment by 1technophile** [comment]
Hi,

Yes once you get the updated `development` branch

**Comment by orxaz** [comment]
Hi.

Ok, will try, not sure if I will be capable :)

Thanks.

**Comment by 1technophile** [comment]
Hi,

I propose to close this PR, if you find the time, do not hesitate to submit a new one from the development branch.

**Pull request closed without merging**
