### PR TITLE
Added board ESP32 DOIT DevKit V1 with SX1278 module Ai-Thinker Ra01

### PR DESCRIPTION
**Pull request by diepeterpan**
## Description:

Added board ESP32 DOIT DevKit V1 with SX1278 module Ai-Thinker Ra01

## Checklist:
  - [X ] The pull request is done against the latest development branch
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
Thanks for the PR, could you add your environement in the action file please:
https://github.com/1technophile/OpenMQTTGateway/blob/a3603c6a788609281743eeb72aaa44ff58a2db4f/.github/workflows/build.yml#L10

**Comment by 1technophile** [comment]
Sorry, I should have merged this one before the change. Can you rebase it please?

**Comment by diepeterpan** [comment]
> Sorry, I should have merged this one before the change. Can you rebase it please?

Hope I did it correctly.

**Comment by 1technophile** [comment]
Thanks!

**Pull request merged**
