### PR TITLE
[BREAKING] Change uptime unit from seconds to minutes

### PR DESCRIPTION
**Pull request by 1technophile**
to prevent going to the max of unsigned long

### CODE REVIEW

**Comment by csiki2** [comment]
Even the signed long (2^31 sec) can hold more than 68 years, do I miss something here? :)

**Comment by 1technophile** [comment]
Thanks for pointing this out, you are right the cause of the issue is not the variable type, it is the limit of millis(). I will find another way.

**Comment by csiki2** [comment]
Something like below?
<pre>
static unsigned long lastUptime = 0;
static unsigned long uptimeAdd = 0;
unsigned long uptime = millis() / 1000 + uptimeAdd;
if (uptime &lt; lastUptime) {
  uptime += 4294967;
  uptimeAdd +=4294967;
}
lastUptime = uptime;
</pre>
I don't know where millis() roll over, I expect to be unsigned long here.

**Comment by csiki2** [comment]
Hmm. millis() seem to use
int64_t esp_timer_get_time();
So actually, we have a proper uptime source, but loose during millis():
<pre>
unsigned long IRAM_ATTR millis()
{
    return (unsigned long) (esp_timer_get_time() / 1000ULL);
}
</pre>
The propes code still should work though.

**Comment by 1technophile** [comment]
Thanks, your first code will work also with Arduino boards, so it will avoid adding more board-specific code. I will push a PR with it.

**Pull request merged**
