### PR TITLE
Add wifi manager portal

### PR DESCRIPTION
**Pull request by 1technophile**
#83 
#15

### CODE REVIEW

**Comment by ctripodi** [comment]
Hi, I tested the version V0.7. I have a suggestion about to include like a parameter in the web config, the mqtt user and mqtt password.
Regards.

**Comment by 1technophile** [comment]
Hi, i will add that thanks for the proposal

**Comment by ctripodi** [comment]
Moreover there is an issue in the mqtt server name in these lines (Function reconnect() ):
#ifdef mqtt_user
      if (client.connect(_**Gateway_Name**_, mqtt_user, mqtt_password, will_Topic, will_QoS, will_Retain, will_Message)) { // if an mqtt user is defined we connect to the broker with authentication
#else
      if (client.connect(_**Gateway_Name**_, will_Topic, will_QoS, will_Retain, will_Message)) {
#endif

The variable with the mqtt server name looks like is incorrect.

**Comment by 1technophile** [comment]
Waiting for this before adding esp32 wifi manager portal:
https://github.com/tzapu/WiFiManager/issues/241

**Comment by 1technophile** [comment]
@ctripodi I don't understand why Gateway_Name is an incorrect variable?

I added mqtt user and password if you could test it could be great

**Comment by ctripodi** [comment]
Hi @1technophile, I completed the test a few minutes ago, all is OK! thanks for your quick update!
Sorry for my last comments about the Gateway_Name, was my mistake.
Great job!

**Comment by ctripodi** [comment]
Hi @1technophile I have a new suggestion about improve the performance of the config web page, I could see that in some cases when there are a lot of WiFi signals availables, te time to load the pague is too much. I am using WifiManager in another projects, So my suggestion is that you could youse a parameter to filter just some wifi signals to show in the scan list.
The parameter is "setMinimumSignalQuality"
    //set minimu quality of signal so it ignores AP's under that quality
    //defaults to 8%
    wifiManager.setMinimumSignalQuality(MinimumSignalQuality);

Regards.

**Comment by 1technophile** [comment]
Added thanks for the feedback!

**Comment by htcheroportugal** [comment]
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started


whats password for this?

**Comment by 1technophile** [comment]
#define WifiManager_password "your_password"

**Pull request merged**
