### PR TITLE
Fix DS18B20 not working properly

### LINKED ISSUE #1118: DS18B20 not working properly
Before submitting a problem please check the troubleshooting section
https://docs.openmqttgateway.com/upload/troubleshoot.html

**Describe the bug**
The discovery of the sensor work fine, but value are never send.
The default value  `DS1820_INTERVAL_SEC 60` don't work, even after 3 minutes, changing to  `DS1820_INTERVAL_SEC 30` make it work. 32 work, 33 not. So we are at the 32.7 seconds limit because of a 16 bit int. More info on the error here : https://forum.arduino.cc/t/unsigned-long-multiplication/108567

When it worked, I saw that the temp are not in the right field:
```
{
    "tempc": 63.14,
    "tempf": 17.3,
    "type": "DS18B20",
    "res": "10bit\n",
    "addr": "0x283d057997020371"
}
```

**To Reproduce**
1. Fresh install with `#define ZsensorDS1820  "DS1820"` uncommented

**Expected behavior**
The sensor value are send on the bus, with Celsius in tempc .

**Environment (please complete the following information):**
* OpenMQTTGateway version used (V0.9.8)
* Arduino Mega + Ethernet

### PR DESCRIPTION
**Pull request by benoit-cty**
## Description:

There is an overflow in millis comparison and a switch between Celcius and Fahrenheit, see https://github.com/1technophile/OpenMQTTGateway/issues/1118

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by benoit-cty** [comment]
I have prepared a fix: https://github.com/benoit-cty/OpenMQTTGateway/commit/8c0c8714bffa5be8830bc2e3a2f4221aafb4ccd0

But I am unable to test it because the development branch don't compile:
```
In file included from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\StringTraits/StringTraits.hpp:36:0,
                 from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\JsonVariantComparisons.hpp:7,
                 from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\JsonVariantBase.hpp:8,
                 from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\JsonVariant.hpp:13,
                 from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\jsonbuffer.hpp:12,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Deserialization/JsonParser.hpp:7,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonBufferBase.hpp:7,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/DynamicJsonBuffer.hpp:7,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:9,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from C:\Users\ben\Documents\Arduino\OpenMQTTGateway\main\main.ino:52:
c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\StringTraits/StdString.hpp:14:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
compilation terminated.
exit status 1
Erreur de compilation pour la carte Arduino Mega or Mega 2560
```

I don't know how to solve it as same ArduinoJson work fine with OpenMQTTGateway last stable.

I tried with ArduinoJson 5.x and 6.x but I got the same error.

**Comment by 1technophile** [comment]
It may be due to the introduction of std :: string and the associate  `include<string>` in main.ino
https://github.com/1technophile/OpenMQTTGateway/blob/66ce0d5a413de9b5d1d5a5ab653ef92f579a5445/main/main.ino#L56

**Comment by benoit-cty** [comment]
> It may be due to the introduction of std :: string and the associate `include<string>` in main.ino
> 
> https://github.com/1technophile/OpenMQTTGateway/blob/66ce0d5a413de9b5d1d5a5ab653ef92f579a5445/main/main.ino#L56

Thanks, but the error raise before this include, and commenting this line don't change the error.
How to add megaatmega2560 target in the Github Action to be sure it's not a local problem ?

`platformio.exe run --environment rfbridge` compile well, but not 'arduino-grenier' with:
```

[platformio]
default_envs = arduino-grenier

[env:arduino-grenier]
platform = ${com.atmelavr_platform}
board = megaatmega2560
lib_deps =
  ${com-arduino.lib_deps}
  ${libraries.onewire}
  ${libraries.dallastemperature}

build_flags =
  ${com-arduino.build_flags}
  '-DZactuatorONOFF="ONOFF"'
  '-DZsensorDS1820="DS1820"'
  ;'-DZsensorGPIOKeyCode="GPIOKeyCode"'
  '-DZmqttDiscovery="HADiscovery"'
  ;'-DsimplePublishing=true'
  '-DGateway_Name="OpenMQTTGateway_ATMEGA_ALL"'
  '-DMQTT_USER="mqttusername"'
  '-DMQTT_PASS="mqttpassword"'
  '-DMQTT_SERVER="mqttserver.local"'
monitor_speed = 115200
```

**Comment by 1technophile** [comment]
> How to add megaatmega2560 target in the Github Action to be sure it's not a local problem ?

It is already checked [here](https://github.com/1technophile/OpenMQTTGateway/blob/5c3eccbb188d7a062ca9b360670a80ea5942c3d1/platformio.ini#L1054)

I reproduce your issue locally, I'm taking a look

**Comment by 1technophile** [comment]
It is due to the introduction of `std::string` and in particular due to [this macro](https://github.com/1technophile/OpenMQTTGateway/blob/5c3eccbb188d7a062ca9b360670a80ea5942c3d1/main/main.ino#L49), if you comment it, it builds

**Comment by 1technophile** [comment]
Adding `${libraries.stl}` to your environment will enable the build :

```
[env:arduino-grenier]
platform = ${com.atmelavr_platform}
board = megaatmega2560
lib_deps =
  ${com-arduino.lib_deps}
  ${libraries.onewire}
  ${libraries.dallastemperature}
  ${libraries.stl}
build_flags =
  ${com-arduino.build_flags}
  '-DZactuatorONOFF="ONOFF"'
  '-DZsensorDS1820="DS1820"'
  ;'-DZsensorGPIOKeyCode="GPIOKeyCode"'
  '-DZmqttDiscovery="HADiscovery"'
  ;'-DsimplePublishing=true'
  '-DGateway_Name="OpenMQTTGateway_ATMEGA_ALL"'
  '-DMQTT_USER="mqttusername"'
  '-DMQTT_PASS="mqttpassword"'
  '-DMQTT_SERVER="mqttserver.local"'
monitor_speed = 115200
```

**Comment by benoit-cty** [comment]
Thank you, it works !

**Comment by 1technophile** [comment]
Thanks for the PR

**Pull request merged**
