### PR TITLE
Fix BME280

### LINKED ISSUE #963: Sensor BME280 is not working
Sensor BME280 is not working (GY-BME280)

Connection
```
3.3v -> VIN
21   -> SDA
22   -> SCL
```
I tried two different sensors I bought 6 month apart
I've tried both sensor with adress 0x77 and 0x76.
I've tried both times with switched SCL/SDA pins

Output on start after the log fix:
```text
************* WELCOME TO OpenMQTTGateway **************
N: OpenMQTTGateway Version: version_tag
[E][WiFiMulti.cpp:184] run(): [WIFI] Connecting Failed.
N: WiFi ok with manual config credentials
N: Setup BME280 on adress: 0x76
N: Bosch BME280 Initialized - Result of .begin(): 0x0
N: IR_EMITTER_GPIO: 14
N: IR_RECEIVER_GPIO: 26
N: OpenMQTTGateway modules: ["BME280","IR"]
N: ************** Setup OpenMQTTGateway end **************


************* WELCOME TO OpenMQTTGateway **************
N: OpenMQTTGateway Version: version_tag
[E][WiFiMulti.cpp:184] run(): [WIFI] Connecting Failed.
N: WiFi ok with manual config credentials
N: Setup BME280 on adress: 0x77
N: Bosch BME280 Initialized - Result of .begin(): 0x0
N: IR_EMITTER_GPIO: 14
N: IR_RECEIVER_GPIO: 26
N: OpenMQTTGateway modules: ["BME280","IR"]
N: ************** Setup OpenMQTTGateway end **************

```

### PR DESCRIPTION
**Pull request by spacemanspiff2007**
Fix log output, since %H never prints anything

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
#951 951

**Comment by spacemanspiff2007** [comment]
#963

**Comment by spacemanspiff2007** [comment]
Initialized BME280, otherwise it will not work

**Comment by spacemanspiff2007** [comment]
I've updated the files so lint should pass now.
The other check seems to fail because of some unrelated reason but I am not sure.

**Comment by h2zero** [comment]
Build error notes:
```
error: no matching function for call to 'TwoWire::begin(int&, int&)'
framework-arduino-avr\libraries\Wire\src/Wire.h:53:10: note: candidate: void TwoWire::begin()
framework-arduino-avr\libraries\Wire\src/Wire.h:54:10: note: candidate: void TwoWire::begin(uint8_t)
framework-arduino-avr\libraries\Wire\src/Wire.h:55:10: note: candidate: void TwoWire::begin(int)
```
AVR  wire library does not accept pins for parameters in the call to `begin()`

I recommend using a conditional check such as:
```
#Ifdef ESP32
  Wire.setPins(BME280_PIN_SDA, BME280_PIN_SCL);
#endif
```
Instead of the `Wire.begin` call that was added.

**Comment by spacemanspiff2007** [comment]
@h2zero 
Thank you for your quick analysis! Do you think it makes sense to just disable this for the AVRs?
I think the esp8266 supports it, too.
What would be the def for that?

**Comment by h2zero** [comment]
@spacemanspiff2007 
>Do you think it makes sense to just disable this for the AVRs?
I think the esp8266 supports it, too.
What would be the def for that?

I do not have the means to test the functionality but you could add the check as:
```
#if defined (ESP8266) || defined(ESP32)
  Wire.setPins(BME280_PIN_SDA, BME280_PIN_SCL);
#endif
```

That should at least compile and I don't see any reason for it to affect the function of all involved.

**Comment by spacemanspiff2007** [comment]
I've done exactly that!
Thank you very much for you help!

**Comment by h2zero** [comment]
No worries 😄 lets hope it works out.

**Comment by h2zero** [comment]
@spacemanspiff2007, sorry I guess 8266 does not have `setPins()`.

You'll need to change the check to this:
```
#  if defined(ESP8266) || defined(ESP32)
  Wire.begin(BME280_PIN_SDA, BME280_PIN_SCL);
#  else
  Wire.begin();
#  endif
```

**Comment by 1technophile** [comment]
Thanks for the PR, for the code format you can take a look below:
`So as to format automaticaly your document you have to add the "clang-Format" extension to VSCode, once done, you can format the code by doing a right click into the code file window and clicking "Format document".`

**Comment by spacemanspiff2007** [comment]
@1technophile 
Thanks for the hint - I'll do this the next time from the beginning.

**Pull request merged**
