### PR TITLE
Initial doc for Jeedom integration

### PR DESCRIPTION
**Pull request by BadWolf42**
## Description:
Initial documentation for OMG integration in Jeedom.

Feel free to comment, I'll update my PR accordingly.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DigiH** [comment]
Great tutorial @BadWolf42 ! Thanks, just

> go smoke a coffee

made me laugh 😄 maybe `go smoke or/and have a coffee`

**Comment by BadWolf42** [comment]
Thanks @DigiH :)
Actually this joke was intended (like "automagically" a bit before) and part of the original how-to on Jeedom Community.
If you prefer that I keep a more professional style, I suggest "Let it run for 5 minutes and have a break, you deserve it"

**Comment by DigiH** [comment]
Oh no!! As I said, it made me laugh, so if that was the intention, by all means leave it as is!! 👍

**Comment by 1technophile** [comment]
@BadWolf42 thanks!

Meanwhile I'm going to smoke a coffee ;-) could you rebase the PR, please ?

**Comment by BadWolf42** [comment]
Rebased!

Hum, sadly I misspelled 'Jeedom' in the branch name...
Do you think that I can "just" rename the branch or you can take care to avoid the typo/branch name on merge?

**Comment by 1technophile** [comment]
Thanks, I think we can let it like this if you agree, the branch can be removed after the merge.

**Comment by BadWolf42** [comment]
Sure, all right 👍

**Pull request merged**
