### PR TITLE
add mqtt discovery (compatibile with home assistant) with omg status …

### PR DESCRIPTION
**Pull request by animavitis**
- added omg status binary sensor
- added bme280 sensors
- anothers sensor can be easy added :)
- OMG device is visible in home assistant integrations  
- All discovered sensors are connected to OMG gateway in integrations

### CODE REVIEW

**Comment by animavitis** [comment]
added for ESP32. Should i add it to other boards too?

**Comment by 1technophile** [comment]
Yes for esp8266 and arduino mega (__AVR_ATmega1280__)

**Comment by animavitis** [comment]
done:)

**Comment by 1technophile** [comment]
It's progressing well :-)

**Comment by 1technophile** [comment]
Maybe we could remove the macro for each attribute and supposing that if there is a bme280 we expose all these?

**Comment by animavitis** [comment]
as u wish:)

**Comment by 1technophile** [comment]
Do you have other optimizations planned or do I integrate it?

**Pull request merged**
