### PR TITLE
[SYS] Add timestamp for messages

### PR DESCRIPTION
**Pull request by dkneisz**
## Description:
- add timestamp when publishing
- add "GMT" as timezone for timestamp (e.g. for openHAB to use the correct time if you are in a different timezone)

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
Thanks for the PR. I think timestamp should be added in the joint pub function (from the main.ino) rather than adding it into each gateway.
This will be easier to maintain and will avoid code duplication.

**Comment by dkneisz** [comment]
I agree. Since it was already implemented in ZgatewayBT.ino I was under the impression, that it is implemented in some other modules also. That's why I just implemented it for ZgatewayRTL_433.ino. Should I implement this here or create another pull request?

**Comment by 1technophile** [comment]
Up to you, I don't mind either solution

**Comment by dkneisz** [comment]
I moved it now to main.ino into the function "void pub(const char* topicori, JsonObject& data)". There are also to additional functions
- void pub(const char* topicori, const char* payload, bool retainFlag)
- void pub(const char* topicori, const char* payload)
but they don't seem to do the same thing. I'm not quite sure where exactly they are used. They just publish the given payload to the given topic, so I didn't change anything there.

I tested this for the following:
- BTtoMQTT
- PilighttoMQTT
- RLStoMQTT
- SYStoMQTT
- WebUItoMQTT
- 433toMQTT
- RTL_433toMQTT
- SSD1306toMQTT

**Comment by 1technophile** [comment]
Thanks

**Comment by DigiH** [comment]
@dkneisz @1technophile

While great to have the time stamp option for all modules, why has the naming here changed from the definitive Z(ulu Time) to an ambiguous, non-existant, ZGMT naming scheme?

What we do get is Zulu time, which is also known as Coordinated Universal Time/Temps Universel Coordonné - abbreviated nonsensically as UTC, so either the previously existing Z or alternatively UTC should be used, but definitely not GMT in any form, as GMT does observe daylight saving time, which for the Coordinated Universal (Zulu) Time we give is incorrect and unwanted for users worldwide. Just to clarify my above comment.

**Comment by dkneisz** [comment]
@DigiH your are right. I was trying to fix an issue I had, that my openHAB used the wrong timezone for this date. Now that you mention it, I'm not sure why this solution worked for me. Even stranger I now reverted the change and my openHAB is now using my timezone. Not sure what happened here. I will revert this change and submit another pull request for this.

**Pull request merged**
