### PR TITLE
Add support for HC-SR04 sensor

### PR DESCRIPTION
**Pull request by mpember**
Adds support for HC-SR04 Ultrasonic distance sensor.

Note: only tested on a Wemos d1 mini board

### CODE REVIEW

**Comment by mpember** [comment]
Updated platformio.ini as requested.  Since I tried to avoid any of my custom settings to contaminate the main repo, I have not actually built this code using a 'clean' platformio.ini.  But I assume this won't be a problem.

**Comment by 1technophile** [comment]
Thanks for the modification, codacy proposes you yo go down the distance declaration into the else : 
 https://app.codacy.com/manual/1technophile/OpenMQTTGateway/pullRequest?prid=4128387

**Comment by mpember** [comment]
I've made the change.  Not sure how to force the tests to run again

**Comment by 1technophile** [comment]
Verifications are done. But you changed duration instead of distance.

**Comment by 1technophile** [comment]
Tests are OK now, thanks for the add!

**Pull request merged**
