### PR TITLE
CC1101 433.92MHz support for pilight, rf and rf2

### PR DESCRIPTION
**Pull request by orrpan**
# Support for CC1101 433.92MHz

## Requires
Requires to install SmartRC-CC1101-Driver-Lib from Arduino Library Manager.

## Wiring
On CC1101
GD00 = RF_EMITTER_PIN
GD02 = RF_RECEIVER_PIN

For the rest of the wires use:
https://github.com/LSatan/SmartRC-CC1101-Driver-Lib#wiring

### ESP
[Joy-IT NODEMCU ESP32](https://joy-it.net/en/products/SBC-NodeMCU-ESP32)
[Wemos D1 Mini (ESP8266)](https://www.ebay.com/itm/D1-ESP8266-Mini-WLAN-Board-Mikrokontroller-Wifi-Modul-Wemos-Nodemcu-Arduino/254535886946)

### CC1101
[NoName CC1101](https://www.ebay.com/itm/CC1101-Wireless-Transceiver-315-433-868-915MHZ-SMA-Antenna-Wireless-Module/152579160704)

#### ZgatewayPilight & ZgatewayRF2
Nexa switch PE-3 and remote

#### ZgatewayRF
EverFlourish remote control plug

### Other info
Only tested 433.92MHz

ESP8266 I had to use 
```cpp
#define RF_RECEIVER_PIN 4
```
```cpp
#define RF_EMITTER_PIN 5
```

It might also work on Arduinos, my nano said it had too little space so I wasn't able to test.

### CODE REVIEW

**Comment by 1technophile** [comment]
Thanks for the PR, could you add the library into [platformio.ini](https://github.com/1technophile/OpenMQTTGateway/blob/1385ddfa8de5fb8ffffe128e6efec7f15ff93a43/platformio.ini#L62) please

And an environment to test your PR:
`;default_envs = nodemcuv2-rf-cc1101`

``` .ini
[env:nodemcuv2-rf-cc1101]
platform = ${com.esp8266_platform}
board = nodemcuv2
lib_deps =
  ${com-esp.lib_deps}
  ${libraries.rcswitch}
  ${libraries.esp8266_mdns}
build_flags =
  ${com-esp.build_flags}
  '-DZgatewayRF="RF"'
  '-DZradioCC1101="CC1101"'
  '-DGateway_Name="OpenMQTTGateway_ESP8266_RF-CC1101"'
board_build.flash_mode = dout
```

**Comment by orrpan** [comment]
okok, Should I create:
;default_envs = esp32dev-rf-cc1101
;default_envs = esp32dev-rf2-cc1101
;default_envs = esp32dev-pilight-cc1101

;default_envs = nodemcuv2-rf-cc1101
;default_envs = nodemcuv2-rf2-cc1101
;default_envs = nodemcuv2-pilight-cc1101

**Comment by 1technophile** [comment]
As proposed you can create also one test environment for esp32

**Comment by orrpan** [comment]
added:
* esp32dev-pilight-cc1101
* nodemcuv2-rf2-cc1101

Then esp32 and esp8266 will be tested. Also RF, RF2 and Pilight

**Comment by 1technophile** [comment]
Do you have other modification to add, or do I integrate it as it is?

**Comment by orrpan** [comment]
No, do you have anything specific  in mind?

**Comment by 1technophile** [comment]
Perfect!

**Pull request merged**
