### PR TITLE
[BT] Device Tracker sync across gateways

### PR DESCRIPTION
**Pull request by DigiH**
Device Tracker sync across gateways - OpenMQTTGateway & Theengs Gateway, to avoid intermittent AWAY statuses

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by bcutter** [comment]
Great. If this works out as expected, the provided device_tracker entities (for usage in Home Assistant) can finally start to be practically used. Reaaaally looking forward to see this merged into and shipped with a final release, as the current massive away/home/away/home behaviour renders the whole purpose of device tracking useless. A real milestone.

**Comment by 1technophile** [comment]
Thanks for the PR.
This is going to be integrated but we have some lifting to do before and also the scope of the feature may be extended.

**Comment by DigiH** [comment]
Closing for the inclusion of 
https://github.com/1technophile/OpenMQTTGateway/pull/2094

**Comment by bcutter** [comment]
https://github.com/1technophile/OpenMQTTGateway/tree/Device-tracker-sync-mod gives a 404.

**Comment by DigiH** [comment]
@bcutter 

https://github.com/1technophile/OpenMQTTGateway/pull/2094

**Pull request closed without merging**
