### PR TITLE
blacklist TPMS from discovery

### PR DESCRIPTION
**Pull request by psarossy**
TPMS devices create the same issues as the other duplicate generating devices described in #1168

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
> TPMS devices create the same issues as the other duplicate generating devices

Thanks for the PR, do you have this behavior with the latest version?

**Comment by psarossy** [comment]
I'm on v0.9.12, which has this behavior (fixed all the other ones from #1168), I didn't see PRs that touch this part hence my PR, but can validate if v0.9.15 does it still if you'd like!

**Comment by 1technophile** [comment]
It has been fixed on the [decoder](https://github.com/theengs/decoder), as I use to have this behavior and not have it anymore. Not finding the commit by the way.

**Comment by 1technophile** [comment]
Closing as fixed into the decoder

**Pull request closed without merging**
