### PR TITLE
[DOC] Add support methods and contributors

### PR DESCRIPTION
**Pull request by 1technophile**

### CODE REVIEW

**Comment by 1technophile** [comment]
@all-contributors please add @Legion2

**Comment by 1technophile** [comment]
@all-contributors please add @Legion2 for the code and review work!

**Comment by 1technophile** [comment]
@all-contributors please add @Alomon31 for the code
@all-contributors please add @8666 for the code
@all-contributors please add @BigDi for the code
@all-contributors please add @ChiefZ for the code
@all-contributors please add @McGr3g0r for the code
@all-contributors please add @HosfordDotMe for the code
@all-contributors please add @PatteWi for the code
@all-contributors please add @QuagmireMan for the code
@all-contributors please add @StryKaizer for the code
@all-contributors please add @Rotzbua for the code
@all-contributors please add @alibahba for the code
@all-contributors please add @balvig for the code
@all-contributors please add @chesterbr for the code
@all-contributors please add @f-reiling for the code
@all-contributors please add @johnou for the code
@all-contributors please add @intractve for the code
@all-contributors please add @jrockstad for the code
@all-contributors please add @jumpalottahigh for the code
@all-contributors please add @kabturek for the code
@all-contributors please add @lrswss for the code
@all-contributors please add @philfifi for the code
@all-contributors please add @orrpan for the code
@all-contributors please add @posicat for the code
@all-contributors please add @steadramon for the code
@all-contributors please add @tjhowse for the code
@all-contributors please add @tht for the code
@all-contributors please add @torwag for the code
@all-contributors please add @zerinrc for the code
@all-contributors please add @Floyddotnet for the code and review
@all-contributors please add @BlackSmith for the code
@all-contributors please add @Landrash for the code
@all-contributors please add @kanttti for the code
@all-contributors please add @mpember for the code
@all-contributors please add @larsenglund for the code
@all-contributors please add @pkozul for the code
@all-contributors please add @belidzs for the code
@all-contributors please add @rickybrent for the code
@all-contributors please add @broekema for the code
@all-contributors please add @crankyoldgit for the code
@all-contributors please add @animavitis for the code
@all-contributors please add @Legion2 for the code, infra, review and ideas
@all-contributors please add @jmw6773 for the code
@all-contributors please add @HannesDi for the code

**Comment by 1technophile** [comment]
@all-contributors please add @Alomon31 for the code

**Comment by 1technophile** [comment]
@all-contributors please add @8666 for the code

**Comment by 1technophile** [comment]
@all-contributors please add @BigDi for the code

**Comment by 1technophile** [comment]
@all-contributors please add @ChiefZ for the code

**Comment by 1technophile** [comment]
@all-contributors please add @McGr3g0r for the code

**Comment by 1technophile** [comment]
@all-contributors please add @HosfordDotMe for the code

**Comment by 1technophile** [comment]
@all-contributors please add @PatteWi for the code

**Comment by 1technophile** [comment]
@all-contributors please add @QuagmireMan for the code

**Comment by 1technophile** [comment]
@all-contributors please add @StryKaizer for the code

**Comment by 1technophile** [comment]
@all-contributors please add @Rotzbua for the code

**Comment by 1technophile** [comment]
@all-contributors please add @alibahba for the code

**Comment by 1technophile** [comment]
@all-contributors please add @balvig for the code

**Comment by 1technophile** [comment]
@all-contributors please add @chesterbr for the code

**Comment by 1technophile** [comment]
@all-contributors please add @f-reiling for the code

**Comment by 1technophile** [comment]
@all-contributors please add @johnou for the code

**Comment by 1technophile** [comment]
@all-contributors please add @intractve for the code

**Comment by 1technophile** [comment]
@all-contributors please add @jrockstad for the code

**Comment by 1technophile** [comment]
@all-contributors please add @jumpalottahigh for the code

**Comment by 1technophile** [comment]
@all-contributors please add @kabturek for the code

**Comment by 1technophile** [comment]
@all-contributors please add @lrswss for the code

**Comment by 1technophile** [comment]
@all-contributors please add @philfifi for the code

**Comment by 1technophile** [comment]
@all-contributors please add @orrpan for the code

**Comment by 1technophile** [comment]
@all-contributors please add @posicat for the code

**Comment by 1technophile** [comment]
@all-contributors please add @steadramon for the code

**Comment by 1technophile** [comment]
@all-contributors please add @tjhowse for the code

**Comment by 1technophile** [comment]
@all-contributors please add @tht for the code

**Comment by 1technophile** [comment]
@all-contributors please add @torwag for the code

**Comment by 1technophile** [comment]
@all-contributors please add @zerinrc for the code

**Comment by 1technophile** [comment]
@all-contributors please add @Floyddotnet for the code and review

**Comment by 1technophile** [comment]
@all-contributors please add @BlackSmith for the code

**Comment by 1technophile** [comment]
@all-contributors please add @Landrash for the code

**Comment by 1technophile** [comment]
@all-contributors please add @kanttti for the code

**Comment by 1technophile** [comment]
@all-contributors please add @mpember for the code

**Comment by 1technophile** [comment]
@all-contributors please add @larsenglund for the code

**Comment by 1technophile** [comment]
@all-contributors please add @pkozul for the code

**Comment by 1technophile** [comment]
@all-contributors please add @belidzs for the code

**Comment by 1technophile** [comment]
@all-contributors please add @rickybrent for the code

**Comment by 1technophile** [comment]
@all-contributors please add @broekema for the code

**Comment by 1technophile** [comment]
@all-contributors please add @crankyoldgit for the code

**Comment by 1technophile** [comment]
@all-contributors please add @animavitis for the code

**Comment by Floyddotnet** [comment]
@all-contributors please add @Floyddotnet for the code

**Comment by 1technophile** [comment]
@all-contributors please add @Legion2 for the code, infra, review and ideas

**Comment by 1technophile** [comment]
@all-contributors please add @jmw6773 for the code

**Comment by 1technophile** [comment]
@all-contributors please add @HannesDi for the code

**Comment by Legion2** [comment]
github actions ignores `[skip ci]` in the commit message, so there are now hundreds of queued jobs🤦

**Comment by Legion2** [comment]
@1technophile with the new github design you can customize the right side menu on the main repository page and hide some unused items like "Packages" and "Environments".

**Comment by 1technophile** [comment]
> github actions ignores [skip ci] in the commit message, so there are now hundreds of queued jobs🤦

I'm going to cancel them

**Comment by 1technophile** [comment]
> @1technophile with the new github design you can customize the right side menu on the main repository page and hide some unused items like "Packages" and "Environments".

Thanks for the info !

**Comment by Legion2** [comment]
I can change the github platformio build action to be skip if there is a [skip ci] in the commit message

**Comment by Rotzbua** [comment]
Sorry that my commit message broke some stuff 😱

**Comment by 1technophile** [comment]
> Sorry that my commit message broke some stuff 😱

It didn't break anything, is just me messing up with a plugin sorry all for the disturbance.

I'm removing this plugin and will do it on a simpler way

**Pull request merged**
