### PR TITLE
[LORA] Allow LORA CUSTOM PINS

### PR DESCRIPTION
**Pull request by nikito7**
## Description:

Fix change pins via *_env.ini

Example code:

```ini
  '-DGateway_Name="OMG_ESP32_LORA"'
  '-DZgatewayLORA="LORA"'
  '-DLORA_BAND=868E6'
  '-DLORA_CUSTOM_PINS'
  '-DLORA_SCK=14'
  '-DLORA_MISO=12'
  '-DLORA_MOSI=13'
  '-DLORA_SS=15'
  '-DLORA_RST=16'
  '-DLORA_DI0=5'
```

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
Thanks, to be consistent with the other gateways and sensors config could you add the ifndef per pin instead
Example : 
```c
 # IFNDEF LORA_SCK
 # DEFINE LORA_SCK 14
 # ENDIF
```

**Comment by nikito7** [comment]
I could try.

From my tests. *_env do not override config_LORA defaults

**Comment by 1technophile** [comment]
Indeed, you need to modify the config_LORA.h with an ifndef for each pins if you want to use them in a *_env.ini, this can be proposed in this PR

**Comment by 1technophile** [comment]
Thanks

**Comment by ViPeR5000** [comment]
:)

**Pull request merged**
