### PR TITLE
[RF] rain_rate_mm_h fix

### PR DESCRIPTION
**Pull request by DigiH**
https://community.openmqttgateway.com/t/rain-rate-mm-h-ignored/2597

as defined in several rtl_433 decoders

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
Thks, original was taken from https://github.com/merbanan/rtl_433/blob/1026deab33372e4fe2e6c1d4c0f3df0c02c491be/examples/rtl_433_mqtt_hass.py#L362

Not sure if we should remove rain_mm_h or keep it added to rain_rate_mm_h

**Comment by DigiH** [comment]
Initially I thought that as well, but in all the rtl_433_ESP decoders I couldn't find any **rain_mm_h** at all, only ever **rain_rate_mm_h**, so not sure where **rain_mm_h** could come from otherwise.

Same for rtl_433 actually, only ever mentioned in the example, probably an old/legacy/wrong entry.

https://github.com/merbanan/rtl_433/pull/2565

**Comment by 1technophile** [comment]
Make sense, maybe we should submit a PR in rtl_433 repo

**Comment by DigiH** [comment]
See my link above :)

**Review by 1technophile — APPROVED** [review]

**Pull request merged**
