### PR TITLE
[RF] Disable the active RF receive when transmitting with RC-Switch and "Kaku"

### PR DESCRIPTION
**Pull request by peshovec**
Pilight RF transmit is behaving this way already.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
Thanks, was this tested with emitting and receiving for the different modules ?

**Comment by peshovec** [comment]
Right now, I am using with this change applied.
Did not run through tests, however this is what I can observe:
The gateway is listening on pilight.
 Can send mqttto433 (trigger my aqua light)
 Can send mqtttorf2 (trigger power outlets)
 The sended from the gateway codes are not catched by the pilight receiver.
 Radio emmited codes (with remote controls) are catched by the gateway
(pilight receiver)

Should I replicate that with the other two receiver modes? If i have to,
will take some time, as I run some longer test right now (and switching to
rf2 will require restart, which i'd like to avoid now)

**Comment by 1technophile** [comment]
> Should I replicate that with the other two receiver modes? 

Yes if possible, As the decoder change can be sensible it is necessary to do a regression testing

**Comment by peshovec** [comment]
Run the tests, results are ok. Details below.

Puted the gateway in RF receive mode. Checked that external signals are
received. Issued few commands to send codes from the gateway. Rechecked
that external signals are still received.

Did the same with RF2 receiver mode

By external signals I mean, pressing RF remote control buttons.

**Pull request merged**
