### PR TITLE
implement minimum rssi filtering

### PR DESCRIPTION
**Pull request by 1technophile**
Implement RSSI based filtering at build time (MinimumRSSI macro) and runtime, see below:
`mosquitto_pub -t home/OpenMQTTGateway/commands/MQTTtoBT/set -m '{"minrssi":-80}'`

To remove the filtering the value can be set to 0

@maxi1134, would it be possible to test the modification?

### CODE REVIEW

**Comment by maxi1134** [comment]
Gave it a try but it won't compile at all now.

Might be me, still trying to figure it out, been on it for an hour now.

**Comment by 1technophile** [comment]
Hello @maxi1134

 Do you confirm that this is working for you?

**Comment by maxi1134** [comment]
Not yet! I should have an answer in a couple hours when I get home from work!

-Maxi1134

**Comment by 1technophile** [comment]
@maxi1134 did you had the chance to test the modification ?

**Comment by maxi1134** [comment]
A tiny bit, I am battling a flu since 5 days.

The command seems to be effective in reducing cross-detection yes!

But I did not optimize their range per room yet.

**Comment by 1technophile** [comment]
Thanks for your feedback, have a good recovery !

**Comment by maxi1134** [comment]
This seems to have a bug.
When setting the Minrssi, It stops broadcasting those to home/Tester/BTtoMQTT/E01126898417
But, it keeps broadcasting to the home-assistant integration located at home/home_presence/Tester

image

Thanks for reading!

**Comment by maxi1134** [comment]
Was this ever looked at?

I don't see any update regarding it.

Thanks!

-Maxi1134

**Comment by 1technophile** [comment]
I did a correction below : 
https://github.com/1technophile/OpenMQTTGateway/commit/55436c29fac31b19e26608e9a17c71e0a7fa8e8b

**Comment by maxi1134** [comment]
Amazing!

Although, I just updated to the last version (Pulled 5 days ago)

And it doesn't seem to work anymore:

image

**Pull request merged**
