### PR TITLE
update temperature unit to work in HA

### PR DESCRIPTION
**Pull request by orrpan**
from "C" and "F" to "°C and "°F"

### CODE REVIEW

**Comment by orrpan** [comment]
I'm not 100% this works with F, have to test a little. (I don't use F but I see that my HA is thinking it also is and C, maybe it only needs one of them and then sets it by language?)

**Comment by 1technophile** [comment]
Thanks foe the PR.

@jw6773 as you already worked on this. Could you give your point of view about this PR ?

**Comment by jmw6773** [comment]
@1technophile,
  I'm sorry. My wife just had our third child, so I don't know when I'll be able to test this fully. 

  I made the recommendation to remove the `°` in PR #703 as Home Assistant was ignoring the unit_of_measurement when the symbol was included and converting the temperature readings to a different unit. Upon removal of the symbol, the `tempc` and `tempf` sensor values displayed the transmitted unit without any conversions.

  From my understanding, which could be wrong, Home Assistant converts temperature values to what the user has set in the `configuration.yaml` file for the [`temperature_unit`](https://www.home-assistant.io/docs/configuration/basic/#temperature_unit) (C or F), or if that isn't defined, what it set for [`unit_system`](https://www.home-assistant.io/docs/configuration/basic/#unit_system) (metric or imperial). 

 In my Home Assistant setup I have the following set in the basic setup.
```
#  unit_system: metric
#  temperature_unit: C
```  

  This is an image from my OMG running current dev branch (just compiled) with an AHT10 sensor.
HA_Discovery

  Below is an image of the same device recompiled only adding the `°` in the AHTx0 mqttDiscovery definitions. (And a custom OMG version number.)
HA_Discovery2

  If we want, we could remove the `tempc` and `tempf` sensor definitions from mqttDiscovery and just transmit one temperature value with the appropriate unit_of_measurement, with the `°` symbol. The user would then rely on Home Assistant to do the conversions to what they have set in their config files. Both C and F values would still be posted to MQTT topics for other applications, but only one included in mqttDiscovery for Home Assistant.

**Comment by orrpan** [comment]
Home assistant seems to kind of understand without the ° symbol. I notice the problem when I used the homekit integration, then home assistant couldn't pass any value to the sensor.

> If we want, we could remove the tempc and tempf sensor definitions from mqttDiscovery and just transmit one temperature value with the appropriate unit_of_measurement, with the ° symbol. The user would then rely on Home Assistant to do the conversions to what they have set in their config files. Both C and F values would still be posted to MQTT topics for other applications, but only one included in mqttDiscovery for Home Assistant.

This sounds good, should I then close this PR, create a new PR or juste remove all tempC and tempF and keep temp with "°C"?  
Btw should it be "temp" or "tem", seems to differ in a few places.

**Comment by 1technophile** [comment]
> My wife just had our third child

Congratulations for you and your family !!!

> This sounds good, should I then close this PR, create a new PR or just remove all tempC and tempF and keep temp with "°C"?

Just remove `tem` and `tempf` from the discovery (keep °C) on this PR or open a new one as you prefer.

`tem` will be removed in all the code later on.

**Comment by jmw6773** [comment]
I tested your branch last night and it is crashing at startup. It's a remote device, so I couldn't get any logs.

However I believe it's because the count of parameters for each of the sensors needs to be updated to match. For example, with the MiFlora sensor, the `MiFloraparametersCount` should be `4` instead of the original `6`.

` #    define MiFloraparametersCount 4`

https://github.com/1technophile/OpenMQTTGateway/blob/e23eb1bb677701adebb93b7345cf4daa2bc3ca63/main/ZgatewayBT.ino#L186-L188

**Comment by orrpan** [comment]
> I tested your branch last night and it is crashing at startup. It's a remote device, so I couldn't get any logs.
> 
> However I believe it's because the count of parameters for each of the sensors needs to be updated to match. For example, with the MiFlora sensor, the `MiFloraparametersCount` should be `4` instead of the original `6`.
> 
> ` # define MiFloraparametersCount 4`
> 
> https://github.com/1technophile/OpenMQTTGateway/blob/e23eb1bb677701adebb93b7345cf4daa2bc3ca63/main/ZgatewayBT.ino#L186-L188

Strange, mine is working. But anyway it seems like a smart thing to fix!

**Comment by 1technophile** [comment]
Thanks!

**Pull request merged**
