### PR TITLE
User friendly manual network configuration

### PR DESCRIPTION
**Pull request by vi7**
## Description:

1. Add ability for user friendly IP address override without the need to touch `User_config.h`
2. Add DNS server option for ESP WiFi STA

NOTE: Tested on Wemos D1 mini (ESP8266) **ONLY**, unfortunately I do not have a possibility to test on Arduino and ESP32

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DigiH** [comment]
Testing on ESP32s and ESP8266s, including Avatto S06 IR and Sonoff RF Bridge - running smoothly.

**Comment by DigiH** [comment]
@vi7 

Could you also add a paragraph about this in the documentation? I think it would fit nicely as a separate NOTE after the NOTE

> ::: warning Note Adding manual WiFi and MQTT credentials …

in

https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/upload/builds.md

Thanks

**Comment by 1technophile** [comment]
Also adding the macros into the following environment: [env:esp32dev-all-test]
So that they get tested

**Comment by vi7** [comment]
@DigiH @1technophile thanks guys for checking this, docs updated as well.

**Comment by DigiH** [comment]
@vi7 

Thanks for the Docs update. Could you also add the network build_flags to the [env:esp32dev-all-test] environment, as @1technophile mentioned? This assures constant tests runs with these flags, to avoid future possible regressions.

https://github.com/1technophile/OpenMQTTGateway/blob/development/environments.ini#L51

Thanks

**Comment by vi7** [comment]
@DigiH done, pls let me know if network parameters (IP, mask etc.) for the test env should be different

**Comment by 1technophile** [comment]
Thanks!

**Pull request merged**
