### PR TITLE
Adding low_pulse

### LINKED ISSUE #1119: MQTTtoONOFF : Add and option to simulate a push button
**Is your feature request related to a problem? Please describe.**
I use a relay board to simulate the push of buttons like a human do on a remote. So I only need to make output up for 500 milliseconds.
To avoid doing complicated configuration in Home Assistant, I would prefer to have such an option in MQTTtoONOFF.

**Describe the solution you'd like**
I'd like to send a MQTT message saying ` {"gpio":49,"cmd":"temp_high"}`.

Here is the code I suggest in the else that just log an error: 
```C
    } else {
      if (ONOFFdata["cmd"] == "temp_high"){
        Log.info(F("MQTTtoONOFF temp_high" CR));
        pinMode(gpio, OUTPUT);
        digitalWrite(gpio, HIGH);
        delay(500);
        digitalWrite(gpio, LOW);
      }else if(ONOFFdata["cmd"] == "temp_low"){
        Log.info(F("MQTTtoONOFF temp_low" CR));
        digitalWrite(gpio, LOW);
        delay(500);
        digitalWrite(gpio, HIGH);
      }else{
        Log.error(F("MQTTtoONOFF failed json read" CR));
      }
    }
```

**Describe alternatives you've considered**
Complicated configuration in Home Assistant, that may failed and it will be a problem if the relay stay in the HIGH state for some applications like remote.

**Additional context**
I could make a PR for that, just tell me if it's sound a good feature.
Jeeduino for Jeedom call this feature "high_pulse", maybe it's a better name ?

### PR DESCRIPTION
**Pull request by benoit-cty**
## Description:

See https://github.com/1technophile/OpenMQTTGateway/issues/1119

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by benoit-cty** [comment]
I am unable to test it because the development branch don't compile at home in Arduino IDE:
```
In file included from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\StringTraits/StringTraits.hpp:36:0,
                 from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\JsonVariantComparisons.hpp:7,
                 from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\JsonVariantBase.hpp:8,
                 from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\JsonVariant.hpp:13,
                 from c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\jsonbuffer.hpp:12,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Deserialization/JsonParser.hpp:7,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonBufferBase.hpp:7,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/DynamicJsonBuffer.hpp:7,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:9,
                 from C:\Users\ben\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from C:\Users\ben\Documents\Arduino\OpenMQTTGateway\main\main.ino:52:
c:\users\ben\documents\arduino\libraries\arduinojson\src\arduinojson\StringTraits/StdString.hpp:14:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
compilation terminated.
exit status 1
Erreur de compilation pour la carte Arduino Mega or Mega 2560
```

**Comment by 1technophile** [comment]
With Arduino IDE maybe try to remove ArduinoJson folder from TheengsDecoder source library folder.

This is what this [script ](https://github.com/theengs/decoder/blob/development/scripts/remove_arduino_json.py) is doing before building.

Note that with PlatformIO `atmega-all-test` build fine locally.

**Comment by 1technophile** [comment]
@benoit-cty Could you update the [docs ](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/use/actuators.md) also please

**Comment by benoit-cty** [comment]
I've added the documentation.

~~But still not able to compile last version locally with Arduino IDE or PlateformIO. But I'm not familiar with both of them.~~

Finally it works in PlateformIO after a "Clean All".

**Comment by 1technophile** [comment]
Cool, thanks for the PR!

**Pull request merged**
