### PR TITLE
Add VegTrug (Mi Flora like) sensor

### PR DESCRIPTION
**Pull request by 1technophile**
https://community.home-assistant.io/t/anyone-used-a-plant-sensor-other-than-xaiomi/150868/2

### CODE REVIEW

**Comment by 1technophile** [comment]
@ChrisSutton123 as I have seems that you are looking for Vegtrug support, would you be interested in testing it with OpenMQTTGateway, we implemented it but I never had any feedback about it?

**Comment by ChrisSutton123** [comment]
Yes I would. I am currently running Home Assistant (HASS.IO) on a Raspberry pi 4. 
Using an ESP32 to interface to a miflora sensor.

**Comment by ChrisSutton123** [comment]
I Tested Development Branch on a ESP32 Dev board, using both miflora and VegTrug sensors.
Both work very well, so far 24hr without problem.

**Comment by 1technophile** [comment]
Great, thanks for the feedback!

**Pull request merged**
