### PR TITLE
INA226 JSON do not output leading spaces

### LINKED ISSUE #1691: INA226 incorrect JSON output
Hello,

JSON output from INA226 sensor is incorrect. Output contain space before values, e.g.:  {"volt": 3.3,...} and it should be {"volt":3.3,...} (without space before value). 

My workaround is to modify "ZsensorINA226.ino" to:
...   
//char volt_c[7];
//char current_c[7];
//char power_c[7];
//dtostrf(volt, 6, 3, volt_c);
//dtostrf(current, 6, 3, current_c);
//dtostrf(power, 6, 3, power_c);
INA226data["volt"] = (float)volt;
INA226data["current"] = (float)current;
INA226data["power"] = (float)power;
...

1. Publish INA226 to MQTT with JSON
2. Use Telegraf "mqtt_consumer" with json output to influxdb to read this topic 
3. InfluxDB/Grafana will be not able to read/graph this data

**Expected behavior**
Valid JSON output format like other sensors.

Thank you. 

Peter

### PR DESCRIPTION
**Pull request by NorbertHD**
## Description:
Closes #1691

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by 1technophile** [comment]
I think the code could be simplified to have:
```c
    INA226data["volt"] = (float)volt;
    INA226data["current"] = (float)current;
    INA226data["power"] = (float)power;
```
And get rid of the `dtostrf`

**Comment by NorbertHD** [comment]
1. Why cast to float? volt, current and power are already of type float.
2. With dtostrf you have exactly 2 decimal places. But with your proposal, you have rounding artifacts.
   e.g. 0.28 gets 0.280000001 or 3.43 gets 3.430000067 in the json data.

So how should we go on?

**Comment by 1technophile** [comment]
1) The casting was a way to specify ArduinoJson the type, but it may not be necessary
https://arduinojson.org/v6/api/config/use_double/

2) is it the responsibility of OMG to choose the number of decimals to display rather than the controller? Still trying to figure out this one. As it is use cases related, we could stick with the behavior of ZsensorHTU21, ZsensorLM75, ZsensorSHTC3, ZsensorDHT not rounding or round it like in ZsensorRN8209
Open to discussion on this

**Comment by NorbertHD** [comment]
I have updated the PR, I think not rounding is the correct way. Data should be transported and stored in full precision and only rounded when displaying.

**Comment by 1technophile** [comment]
Thanks

**Pull request merged**
