### PR TITLE
ESPilight support

### PR DESCRIPTION
**Pull request by steadramon**
Support for ESPilight - only receive at the moment

I've put the if's around enabling as it doesn't seem to work for me at the moment. I'm working on the sending - looking into the multiple wildcard subscription for the subjects.

### CODE REVIEW

**Comment by 1technophile** [comment]
Hello,

Thanks for this PR could you add in test/test_config.h 
#define ZgatewayPilight  "Pilight"
So as to test that the compilation is working. You will need to add the pilight library into lib folder.

**Comment by 1technophile** [comment]
@steadramon Do you think you could update test_config.h and add the emitter part?

**Comment by steadramon** [comment]
Apologies - been on holiday last few weeks - will get this updated once I've got caught up with real life :)

**Comment by 1technophile** [comment]
no problem :-)

**Comment by thundergreen** [comment]
Any news here ?

**Comment by steadramon** [comment]
Transmit was done in commit 50ddbd7

I think I've updated the Test_config as required?

**Comment by 1technophile** [comment]
Thanks @steadramon. @thundergreen do you think you could test the pull request before integration to the master branch ?

**Comment by 1technophile** [comment]
@steadramon an user seems to have issue to send commands to elro switch: 
https://community.openmqttgateway.com/t/correct-message-for-mqtttopilight/257/2

Do you have some idea to help ?

**Comment by steadramon** [comment]
Looks like a slight mismatch for the send function in the PiLight library I used - it's currently missing the repeats - I'll have to submit you another PR ... get back to you asap

**Pull request merged**
