### PR TITLE
Add Switchbot support and discovery.

### PR DESCRIPTION
**Pull request by h2zero**
Adds Switchbot support and automatic discovery for Home Assistant and OpenHAB. 

Improves BLE command support by using a one-shot task to process immediate BLE actions, this prevents MQTT disconnections if the action takes too long to complete.

Adds state_on and state_off parameters to createDiscovery().

### CODE REVIEW

**Comment by darkjavi** [comment]
Just received 4 MagicSwitchbot units and can try this. Already compiled and uploaded the firmware in the pr but cannot figure out the command I have to send to trigger the switch.

Im guessing its a write command like the one in ble.md

mosquitto_pub -t home/OpenMQTTGateway/commands/MQTTtoBT/config -m '{
  "ble_write_address":"AA:BB:CC:DD:EE:FF",
  "ble_write_service":"cba20d00-224d-11e6-9fb8-0002a5d5c51b",
  "ble_write_char":"cba20002-224d-11e6-9fb8-0002a5d5c51b",
  "ble_write_value":"TEST",
  "value_type":"STRING",
  "ttl":4 }'

but with the correct mac and payload.
any hint?

**Comment by h2zero** [comment]
@darkjavi That should be working, I do not know what value / value type the switchbot needs to receive but you may need to change that as well.

**Comment by darkjavi** [comment]
been looking to this python lib to manage the switchbot:
https://github.com/OpenWonderLabs/python-host/blob/master/switchbot.py

    if act == "Turn On":
        con.sendline('char-write-cmd ' + cmd_handle + ' 570101')
    elif act == "Turn Off":
        con.sendline('char-write-cmd ' + cmd_handle + ' 570102')
    elif act == "Press":
        con.sendline('char-write-cmd ' + cmd_handle + ' 570100')
    elif act == "Down":
        con.sendline('char-write-cmd ' + cmd_handle + ' 570103')
    elif act == "Up":
        con.sendline('char-write-cmd ' + cmd_handle + ' 570104')
        
Looks like it needs a handle+fixed command , don't know yet how to generate that and the char-write-cmd

**Comment by h2zero** [comment]
@darkjavi I used this https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32/blob/main/SwitchBot-BLE2MQTT-ESP32.ino as a reference for the basic implementation. Maybe that will help.

**Comment by nielsfaber** [comment]
I have 2 SwitchBot curtains which I want to integrate with Home Assistant.
I tried compiling and running this branch on an ESP32 via Arduino SDK, but couldn’t reach very far unfortunately.
I can confirm that the SwitchBots are seen (their MACs are showing up in the MQTT traffic).
The additional steps needed for open/close functionality and reading the state info are unclear to me.
I switched now to https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32 which gives a very good out-of-the-box experience (curtains show up as cover entities in HA through discovery).
This PR looks very promising as I like OMG for versatility but i think I’m missing some steps/docs to get it up-and-running.
If anyone could give some pointers I would happily try again.

**Comment by h2zero** [comment]
Thanks for the feedback and the link. I am looking for specifics on the commands to interface with the switchbots as I do not have any. This is just a base framework to expand on. If you know the data and commands to read/write for your application please post the info and I'll be glad to write docs and or update the code for support.

**Comment by h2zero** [comment]
Bump, not stale.

**Comment by DigiH** [comment]
Hi @h2zero @1technophile I'm wondering how this project for SwitchBot connectivity is planned for the future? Like with the recent SwitchBot S1 status decoder this could allow for all READ commands info to be substituted by the advertised broadcast information through status decoders, while WRITE commands are issued through this connectivity implementation through a encoder-like substitution in place of the raw hex commands?!?

I'm just wondering if a split implementation like this is planned, or if all WRITE and READ will be implemented here?

If the former, and with the detailed SwitchBot APIs, which @1technophile linked to and the S1 decoder is based on, I'd be happy to work on the other SwitchBot devices' status decoder implementations, like @nielsfaber's SwitchBot curtains etc.

With the API info the WRITE commands should also be clearly defined.

Thanks

**Comment by 1technophile** [comment]
Hi @DigiH,

I'm planning to integrate the new version of the decoder and leverage it for identifying the SwitchBot S1, once identified we will auto-discover those as a switch or press button depending on the mode.
I'm planning to use the regular connectivity implementation for the WRITE commands and to avoid READ through the connection

So yes you can go ahead and implement the Switchbot devices that you want, it will be a great contribution to the decoder!

**Comment by DigiH** [comment]
Hi @1technophile sounds great, thanks for the info. I already created a Curtain status decoder at

https://github.com/DigiH/decoder/tree/switchbot-curtain

So @nielsfaber or anyone else with the SwitchBot Curtain if you could test this version, as the test cases I included are only based on the API documentation, but no real world device testing.

Currently the decoder contains the status for **motionstate**, **position**, **calibrated** (only gets published if state is false, i.e. calibration is needed), **lightlevel** and **battery**.

`Bit [7] – Whether to allow connection 1- allowed, 0- not allowed `

is not currently implemented, but might actually be needed/helpful for WRITE connections.

Probably best to move any further discussions of SwitchBot devices' status decoders here

https://github.com/theengs/decoder/discussions/95

and leave this for further control implementation exchange.

Thanks

**Comment by h2zero** [comment]
Rebased now to latest development branch, needed to bump decoder version also.

**Comment by 1technophile** [comment]
@nielsfaber @darkjavi This PR adds Switchbot S1 (button) autodiscovery and control, would you like to test it?
Note that we don't support password for the moment

**Comment by nielsfaber** [comment]
@1technophile thanks for your efforts, sounds great!
I only have the SwitchBot curtain modules, so I can only test those. Is this included in this version?

As said in my previous comment, at this point I do not know how to send (or request) the open/closed state of these modules, so I would need some help regarding the topic/payload data that is used (unless they are automatically added as cover entities in HA).

**Comment by DigiH** [comment]
Hi @nielsfaber, did you ever get a chance to test the SwitchBot curtain status decoder I mentioned above? 

While it doesn't allow you to send commands to the SwitchBot curtain modules, it shows you their current status (motion state, position, calibration status, light level and battery) and status changes which you might have initiated through the SwitchBot app so far, and similarly to the current SwitchBot S1 implementation is part of getting a full SwitchBot curtain OMG inclusion ready.

If you feel like testing the status decoder and giving some feedback please use the SwitchBot decoder discussion

https://github.com/theengs/decoder/discussions/95

Thanks

**Pull request merged**
