### PR TITLE
fix wrong time format for UTC timestamp

### PR DESCRIPTION
**Pull request by dkneisz**
## Description:
fixes wrong format of timestamp introduced with #1677 

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DigiH** [comment]
Hi @dkneisz thanks for the fix of the time zone naming. 

Now that we have the chance, and as Z(ulu) time and UTC are identical, but UTC is generally being used to define time zones around the world with UTC +/- X, and it being less militaristic than Zulu time …

@dkneisz @1technophile 
… should we finalise it with a change to UTC? 

Would that also work with your OpenHAB set up?

**Comment by dkneisz** [comment]
@DigiH I'm not sure what you mean by that. The "Z" in the UTC time just means that I's in the GMT timezone. Alternatively you could use "+0000" for that. Another option would be to just set the local timezone and use that in the UTC timestamp, but for some reason the function "gmtime" is used there.

**Comment by DigiH** [comment]
The function **gmtime** gives back the UTC - to just add a bit more to the naming confusion, as GMT strictly speaking is also identical to UTC and Z, but historically has changed and therefore still has different meanings for different people.

All I thought was that instead using the formatting "yyyy-MM-ddThh:mm:ssZ", we could have "yyyy-MM-ddThh:mm:ssUTC" for easier international recognition of the time stamp we give.

Let me quickly test it here …

**Comment by DigiH** [comment]
So with

```
  char buffer[sizeof "yyyy-MM-ddThh:mm:ssUTC"];
  strftime(buffer, sizeof buffer, "%FT%TUTC", gmtime(&now));
```

and then getting

`…"UTCtime":"2023-06-16T14:13:00UTC"…`

I just thought it might avoid possible confusion for some users with the Z, but with the key already saying UTCtime all is fine either way :) 

Merging with the original Z

Thanks

**Pull request merged**
