### PR TITLE
Add esp32-wt32-eth01 ethernet board

### LINKED ISSUE #1063: WT32-ETH01 support
**Is your feature request related to a problem? Please describe.**
no, just a feature request - support of new device

**Describe the solution you'd like**
support WT32-ETH01 board from Wireless-Tag

**Describe alternatives you've considered**
build for esp32-olimex-gtw-ble-eth (the only ethernet-enabled device with OMG support) does not run on this board, therefore I am opening this request.

**Additional context**
ESP_Easy_mega_20210802_normal_ESP32_4M316k_ETH-factory.bin works properly on this board, ethernet is working as it should

Hi, I came across these modules and I like they have Ethernet. I'd like to have a BLE>Ethernet interface from this thingy. Do you think you can make OMG run on this board please? If I'm not mistaken, it does not run on this yet. If I'm wrong, could you please direct me what to upload to it?

thanks

### PR DESCRIPTION
**Pull request by 1technophile**
## Description:
See #1063 

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/1technophile/OpenMQTTGateway/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by mgx0** [comment]
nope, something's not right

```
-� 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
N: 
************* WELCOME TO OpenMQTTGateway **************
N: OpenMQTTGateway Version: version_tag
E (1033) emac: Timed out waiting for PHY register 0x2 to have value 0x0007(mask 0xffff). Current value 0xffff
E (2034) emac: Timed out waiting for PHY register 0x3 to have value 0xc0f0(mask 0xfff0). Current value 0xffff
E (2035) emac: Initialise PHY device Timeout
[E][ETH.cpp:105] begin(): esp_eth_enable error: -1
```

**Comment by mgx0** [comment]
I'm not very experienced in such development but looks like user_config.h line 87-94 overwrites the #defines that comes from env in platformio.ini

when I make a change un user_config to include this, it works for WT32-ETH01 board

```
#ifdef ESP32_ETHERNET
#  define ETH_PHY_ADDR  1
#  define ETH_PHY_TYPE  ETH_PHY_LAN8720
#  define ETH_PHY_POWER 16
#  define ETH_PHY_MDC   23
#  define ETH_PHY_MDIO  18
#  define ETH_CLK_MODE  ETH_CLOCK_GPIO0_IN
#endif
```

**Comment by 1technophile** [comment]
You are right, just pushed a correction

**Comment by mgx0** [comment]
works perfectly!

**Pull request merged**
