### PR TITLE
Concat OMG's Short Name to each sensor name

### PR DESCRIPTION
**Pull request by jmw6773**
The Gateway_Short_Name is added as a prefix to each sensor name in ZmqttDiscovery so that they are grouped/searchable within Home Assistant. ( Brought up in Issue #599 )

I'm not sure if using the String concat is the most efficient method to do this, but as the method is only run once per sensor per boot, it shouldn't cause issues or slowdown.

### CODE REVIEW

**Comment by jmw6773** [comment]
Should mention that this could be a Breaking Change for users that are upgrading from a previous version of OpenMQTTGateway and have it configured in Home Assistant. 

The name and entity_id will change for each sensor, requiring the user to update their Home Assistant UI, automations, and another location they are using the entity_id.

**Comment by 1technophile** [comment]
Do you know if there is an easy way to update the entities in bulk in HA?

**Comment by jmw6773** [comment]
I don't really use MQTT Discovery in Home Assistant, so I'm not sure to to update entities in HA.

Looking further into this, the way mqttDiscovery might need to be rethought for some of the elements. As it is now, it can be confusing when you have multiple OMG's connected.

If entity_id isn't unique, Home Assistant postfix's a counter on the end of the entity_id. This makes it more difficult to identity which sensor belongs to which device. 

Sensors directly attached to OMG and the internal commands (erase/restart) should probably be prefixed using the full Gateway Name so they are easily identified/unique and match the devices' name.

```
sensor.restart_omg --> sensor.openmqttgateway_restart_omg
sensor.adc         --> sensor.openmqttgateway_adc
```

Should sensors that are created from wireless devices (i.e. BT), have a unique identifier in their entity_id as well? (I have 2 MiBands at my house. Should the MAC be in the Entity_ID to make them identifiable? Or at least in the MQTT packet sent with the MiBand Steps information?)

sensor.omg_restart_omg belongs to which device?
Is it guaranteed that sensor.omg_erase_omg belongs to the same device?
HA_discovery

**Comment by 1technophile** [comment]
> Should sensors that are created from wireless devices (i.e. BT), have a unique identifier in their entity_id as well?

In my point of view yes, devices not physically attached to OMG should have an unique identifier accross the different gateways that detected it, but for easy searching we can add the fact that they have been discovered by OMG, the mac adress is a good way to do that. Something like sensor.OMG_582D3450FDAF_miband_steps maybe?

> Or at least in the MQTT packet sent with the MiBand Steps information?)
> sensor.omg_restart_omg belongs to which device?
> Is it guaranteed that sensor.omg_erase_omg belongs to the same device?

The devices physically attached or functions (erase, restart) may take the mac adress of the gateway itself or the Gateway_Name with also the short name concatenation (to have a consistent way of searching).

That's some ideas, I'm open to other proposals.

By the way thanks for your help :-)

**Comment by jmw6773** [comment]
Let's cancel this Pull Request for now and have a think about what would work best for HADiscovery.

I think there are two or three issues that need to be discussed and resolved first. Merging this pull request without thinking it though may cause more issues for users and future builds.

**Comment by 1technophile** [comment]
I agree, maybe it may be good to start a thread here to reach opinions:
https://community.openmqttgateway.com/

**Comment by jmw6773** [comment]
Thank you for your time in this awesome project. I hope I can help a little.

[Discussion thread created](https://community.openmqttgateway.com/t/notes-on-issues-with-ha-discovery/953)

**Pull request closed without merging**
